/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ExpenseEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "challenges"
      | "lockStake"
      | "resolveFailure"
      | "resolveSuccess"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "StakeBurned" | "StakeLocked" | "StakeReturned"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "challenges", values: [string]): string;
  encodeFunctionData(functionFragment: "lockStake", values: [string]): string;
  encodeFunctionData(
    functionFragment: "resolveFailure",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveSuccess",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "challenges", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "resolveFailure",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveSuccess",
    data: BytesLike
  ): Result;
}

export namespace StakeBurnedEvent {
  export type InputTuple = [
    challengeId: string,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [challengeId: string, user: string, amount: bigint];
  export interface OutputObject {
    challengeId: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeLockedEvent {
  export type InputTuple = [
    challengeId: string,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [challengeId: string, user: string, amount: bigint];
  export interface OutputObject {
    challengeId: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeReturnedEvent {
  export type InputTuple = [
    challengeId: string,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [challengeId: string, user: string, amount: bigint];
  export interface OutputObject {
    challengeId: string;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ExpenseEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): ExpenseEscrow;
  waitForDeployment(): Promise<this>;

  interface: ExpenseEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  challenges: TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, boolean] & {
        user: string;
        amount: bigint;
        isResolved: boolean;
      }
    ],
    "view"
  >;

  lockStake: TypedContractMethod<[challengeId: string], [void], "payable">;

  resolveFailure: TypedContractMethod<
    [challengeId: string],
    [void],
    "nonpayable"
  >;

  resolveSuccess: TypedContractMethod<
    [challengeId: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "challenges"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, bigint, boolean] & {
        user: string;
        amount: bigint;
        isResolved: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockStake"
  ): TypedContractMethod<[challengeId: string], [void], "payable">;
  getFunction(
    nameOrSignature: "resolveFailure"
  ): TypedContractMethod<[challengeId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveSuccess"
  ): TypedContractMethod<[challengeId: string], [void], "nonpayable">;

  getEvent(
    key: "StakeBurned"
  ): TypedContractEvent<
    StakeBurnedEvent.InputTuple,
    StakeBurnedEvent.OutputTuple,
    StakeBurnedEvent.OutputObject
  >;
  getEvent(
    key: "StakeLocked"
  ): TypedContractEvent<
    StakeLockedEvent.InputTuple,
    StakeLockedEvent.OutputTuple,
    StakeLockedEvent.OutputObject
  >;
  getEvent(
    key: "StakeReturned"
  ): TypedContractEvent<
    StakeReturnedEvent.InputTuple,
    StakeReturnedEvent.OutputTuple,
    StakeReturnedEvent.OutputObject
  >;

  filters: {
    "StakeBurned(string,address,uint256)": TypedContractEvent<
      StakeBurnedEvent.InputTuple,
      StakeBurnedEvent.OutputTuple,
      StakeBurnedEvent.OutputObject
    >;
    StakeBurned: TypedContractEvent<
      StakeBurnedEvent.InputTuple,
      StakeBurnedEvent.OutputTuple,
      StakeBurnedEvent.OutputObject
    >;

    "StakeLocked(string,address,uint256)": TypedContractEvent<
      StakeLockedEvent.InputTuple,
      StakeLockedEvent.OutputTuple,
      StakeLockedEvent.OutputObject
    >;
    StakeLocked: TypedContractEvent<
      StakeLockedEvent.InputTuple,
      StakeLockedEvent.OutputTuple,
      StakeLockedEvent.OutputObject
    >;

    "StakeReturned(string,address,uint256)": TypedContractEvent<
      StakeReturnedEvent.InputTuple,
      StakeReturnedEvent.OutputTuple,
      StakeReturnedEvent.OutputObject
    >;
    StakeReturned: TypedContractEvent<
      StakeReturnedEvent.InputTuple,
      StakeReturnedEvent.OutputTuple,
      StakeReturnedEvent.OutputObject
    >;
  };
}
